kafkador:
  url: http://localhost:8080/
  connectionServiceImplementation:
  services:
    connection:
      implementation: "ConnectionServiceByConfig"
  connections:
    - id: 1
      name: connection-1
      host: 192.168.2.139
      port: 9092
    - id: 2
      name: connection-2
      host: 192.168.2.139
      port: 9095

spring:
  application:
    name: dashboard
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout:
      seconds: 365d # TODO: update
  h2:
    console:
      enabled: true
      path: /h2
