kafkador:
  url: http://localhost:8080/

spring:
  application:
    name: dashboard
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout:
      seconds: 900
  h2:
    console:
      enabled: true
      path: /h2
